version: '3'
services:
  datatiku:
    image: dataiku/dss
    volumes:
      - dataiku-data:/home/dataiku/dss
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.${STACK_NAME?Variable not set}.dataiku-data == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefic-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${STACK_NAME?Variable not set}-dataiku-http.rule=Host(`dataiku.${DOMAIN?Variable not set}`)
        - traefik.http.routers.${STACK_NAME?Variable not set}-dataiku-http.entrypoints=http
        - traefik.http.routers.${STACK_NAME?Variable not set}-dataiku-http.middlewares=${STACK_NAME?Variable not set}-https-redirect
        - traefik.http.routers.${STACK_NAME?Variable not set}-dataiku-https.rule=Host(`dataiku.${DOMAIN?Variable not set}`)
        - traefik.http.routers.${STACK_NAME?Variable not set}-dataiku-https.entrypoints=https
        - traefik.http.routers.${STACK_NAME?Variable not set}-dataiku-https.tls=true
        - traefik.http.routers.${STACK_NAME?Variable not set}-dataiku-https.tls.certresolver=le
        - traefik.http.services.${STACK_NAME?Variable not set}-dataiku.loadbalancer.server.port=10000

volumes:
  dataiku-data:

networks:
  traefik-public:
    external: true
